// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package danmaku

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// DanmakuDaemonClient is the client API for DanmakuDaemon service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DanmakuDaemonClient interface {
	StartWatcher(ctx context.Context, in *WatcherRequest, opts ...grpc.CallOption) (*WatcherResponse, error)
	StopWatcher(ctx context.Context, in *WatcherRequest, opts ...grpc.CallOption) (*WatcherResponse, error)
	KeepAlive(ctx context.Context, in *WatcherRequest, opts ...grpc.CallOption) (*WatcherResponse, error)
	IsAlive(ctx context.Context, in *WatcherRequest, opts ...grpc.CallOption) (*WatcherResponse, error)
}

type danmakuDaemonClient struct {
	cc grpc.ClientConnInterface
}

func NewDanmakuDaemonClient(cc grpc.ClientConnInterface) DanmakuDaemonClient {
	return &danmakuDaemonClient{cc}
}

func (c *danmakuDaemonClient) StartWatcher(ctx context.Context, in *WatcherRequest, opts ...grpc.CallOption) (*WatcherResponse, error) {
	out := new(WatcherResponse)
	err := c.cc.Invoke(ctx, "/danmaku.DanmakuDaemon/StartWatcher", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *danmakuDaemonClient) StopWatcher(ctx context.Context, in *WatcherRequest, opts ...grpc.CallOption) (*WatcherResponse, error) {
	out := new(WatcherResponse)
	err := c.cc.Invoke(ctx, "/danmaku.DanmakuDaemon/StopWatcher", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *danmakuDaemonClient) KeepAlive(ctx context.Context, in *WatcherRequest, opts ...grpc.CallOption) (*WatcherResponse, error) {
	out := new(WatcherResponse)
	err := c.cc.Invoke(ctx, "/danmaku.DanmakuDaemon/KeepAlive", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *danmakuDaemonClient) IsAlive(ctx context.Context, in *WatcherRequest, opts ...grpc.CallOption) (*WatcherResponse, error) {
	out := new(WatcherResponse)
	err := c.cc.Invoke(ctx, "/danmaku.DanmakuDaemon/IsAlive", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DanmakuDaemonServer is the server API for DanmakuDaemon service.
// All implementations must embed UnimplementedDanmakuDaemonServer
// for forward compatibility
type DanmakuDaemonServer interface {
	StartWatcher(context.Context, *WatcherRequest) (*WatcherResponse, error)
	StopWatcher(context.Context, *WatcherRequest) (*WatcherResponse, error)
	KeepAlive(context.Context, *WatcherRequest) (*WatcherResponse, error)
	IsAlive(context.Context, *WatcherRequest) (*WatcherResponse, error)
	mustEmbedUnimplementedDanmakuDaemonServer()
}

// UnimplementedDanmakuDaemonServer must be embedded to have forward compatible implementations.
type UnimplementedDanmakuDaemonServer struct {
}

func (UnimplementedDanmakuDaemonServer) StartWatcher(context.Context, *WatcherRequest) (*WatcherResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StartWatcher not implemented")
}
func (UnimplementedDanmakuDaemonServer) StopWatcher(context.Context, *WatcherRequest) (*WatcherResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StopWatcher not implemented")
}
func (UnimplementedDanmakuDaemonServer) KeepAlive(context.Context, *WatcherRequest) (*WatcherResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method KeepAlive not implemented")
}
func (UnimplementedDanmakuDaemonServer) IsAlive(context.Context, *WatcherRequest) (*WatcherResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method IsAlive not implemented")
}
func (UnimplementedDanmakuDaemonServer) mustEmbedUnimplementedDanmakuDaemonServer() {}

// UnsafeDanmakuDaemonServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DanmakuDaemonServer will
// result in compilation errors.
type UnsafeDanmakuDaemonServer interface {
	mustEmbedUnimplementedDanmakuDaemonServer()
}

func RegisterDanmakuDaemonServer(s grpc.ServiceRegistrar, srv DanmakuDaemonServer) {
	s.RegisterService(&DanmakuDaemon_ServiceDesc, srv)
}

func _DanmakuDaemon_StartWatcher_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WatcherRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DanmakuDaemonServer).StartWatcher(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/danmaku.DanmakuDaemon/StartWatcher",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DanmakuDaemonServer).StartWatcher(ctx, req.(*WatcherRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DanmakuDaemon_StopWatcher_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WatcherRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DanmakuDaemonServer).StopWatcher(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/danmaku.DanmakuDaemon/StopWatcher",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DanmakuDaemonServer).StopWatcher(ctx, req.(*WatcherRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DanmakuDaemon_KeepAlive_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WatcherRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DanmakuDaemonServer).KeepAlive(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/danmaku.DanmakuDaemon/KeepAlive",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DanmakuDaemonServer).KeepAlive(ctx, req.(*WatcherRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DanmakuDaemon_IsAlive_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WatcherRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DanmakuDaemonServer).IsAlive(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/danmaku.DanmakuDaemon/IsAlive",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DanmakuDaemonServer).IsAlive(ctx, req.(*WatcherRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// DanmakuDaemon_ServiceDesc is the grpc.ServiceDesc for DanmakuDaemon service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DanmakuDaemon_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "danmaku.DanmakuDaemon",
	HandlerType: (*DanmakuDaemonServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "StartWatcher",
			Handler:    _DanmakuDaemon_StartWatcher_Handler,
		},
		{
			MethodName: "StopWatcher",
			Handler:    _DanmakuDaemon_StopWatcher_Handler,
		},
		{
			MethodName: "KeepAlive",
			Handler:    _DanmakuDaemon_KeepAlive_Handler,
		},
		{
			MethodName: "IsAlive",
			Handler:    _DanmakuDaemon_IsAlive_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/deamon.proto",
}
